[profile.default]
src = "src"
out = "out"
libs = ["lib"]

fs_permissions = [{ access = "read", path = "./multisig-members.json" }]

evm_version = "cancun"
optimizer = true
optimizer-runs = 200
solc = "0.8.23"
via_ir = false
