= Protocol Factory

== Description

OSx is a complex protocol which requires a non trivial deployment process. Complex processes are error-prone and could lead to unadverted mistakes that compromise the security of the entire deployment.

The Protocol Factory contains a set of contracts that encapsulate and abstract the deployment of OSx, the Management DAO and the Core plugins build by Aragon.

=== Goals

To ensure the soundness and verifiability of any OSx deployment, the Protocol Factory is designed to fulfill the following guarantees:
- The deployment process should be atomic (all or nothing)
- The deployer's wallet should hold no privilege whatsoever (not even temporarily)
- The deployment parameters should be transparent, and verifiable
- The logic of the deployment should be entirely verifiable via the source code
- The factory can only be used once
- The factory becomes read-only afterwards
    - Anyone can read the deployed addresses, as well as the deployment parameters used
- No reverse engineering is required

These properties ensure that not just the protocol contracts but also the deployment itself is end-to-end verifiable.

== Constraints

Due to the inherent limitations of the EVM, the factory cannot contain the bytecode of all the contracts without exceeding the code size limit. This forces the bytecode to be split in several transactions.

- The implementation contracts used as a proxy are deployed by the Foundry deployment script (`Deploy.s.sol`).
- For contracts that need to be a static instance (deployed like `new MyContract()`, the factory uses helper factories. They deploy a new instance, given the parameters passed by the main factory.

Even if the raw deployments are split out, the protocol orchestration and configuration remain entirely on-chain and fully verifiable.

== Use cases

The Protocol Factory serves two main use cases.

- xref:deployment.adoc[Deploying the protocol] to a new chain
- xref:osx-local-testing.adoc[Deploying a local OSx deployment for Plugin development]
